#!/bin/bash
# Author: Andika Ageng P.

CONT_NAME=tensorflow-gpu
CONT_FILTER=$(docker container ls -q -f name=$CONT_NAME)

if [ "$CONT_FILTER" == "" ]; then
   docker start $CONT_NAME
fi

docker exec $CONT_NAME jupyter server list
